config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    get 'join'
    get 'hooray'
    get 'upset'
  end

  root 'welcome#index'

  resources :guests do
    get 'join'
    get 'hooray'
    get 'upset'
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/guest.rb
class Guest < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :visit)
    end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def index
    @guests = Guest.all
  end

  def new
  end

  def create
    @guest=Guest.new(name: params[:guest][:name])
    @guest.save
    redirect_to guests_path
  end

  def show
    @guest = Guest.find(params[:id])
  end

  def join
    @guest=Guest.find(params[:guest_id])
    if params[:visit] == 'yes'
      @guest.visit = true
      @guest.save!
      respond_to do |format|
        format.html {
          redirect_to guest_hooray_path
        }
      end
    else
      @guest.visit = false
      @guest.save!
      respond_to do |format|
        format.html {
          redirect_to  guest_upset_path
        }
      end
    end


  end

  def hooray

  end

  def upset

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :visit %><br>
    <%= f.check_box :visit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Visit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.name %></td>
        <td><%= article.visit %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Visit:</strong>
  <%= @article.visit %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/guests/hooray.html.erb
<div class="container">
  <h1>Hooray! We are waiting for you!</h1>
  <%= image_tag('fireworks2.gif', class:'fireworks img-thumbnail') %>
</div>

app/views/guests/index.html.erb
<% @guests.each do |guest| %>
    <ul>
      <li><%= link_to guest.name, guest_path(guest.id) %><%= image_tag('link_head.png', class:"my-list") if guest.visit %></li>
    </ul>
<% end %>

app/views/guests/new.html.erb
<%= form_for :guest, url: guests_path do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/guests/show.html.erb
<div class="container">
  <h1>Hi <%= @guest.name %></h1>

  <h2>We are happy to invite your family to celebrate Zakhar's birthday with us.</h2>
  <h3>Please check the links below and let us know if you are going to join us.</h3>
</div>

<div class="col-md-12 main-block">
  <div class="col-md-6 col-md-offset-1">
    <iframe width="660" height="415" src="https://www.youtube.com/embed/0XVkumJMDRs" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="col-md-5">
    <div class="col-md-12">
      <%= image_tag("link_head.png", class: "img-responsive link_pic col-md-3") %>
      <h2>Saturday, 3pm</h2>
      <h3>July 2, 2016</h3>
    </div>
    <div class="col-md-12">
      <%= image_tag("link_head.png", class: "img-responsive link_pic col-md-3") %>
      <h2>Lake Accotink Park</h2>
      <h3>7500 Accotink Park Rd, Springfield, VA 22150</h3>
      <div>
        <%= image_tag("shelter.png", class: "mg-responsive shelter img-thumbnail") %>
      </div>
    </div>
  </div>
</div>

<br><br>
<hr>

<div class="col-md-12">
  <div>
    <%= link_to "Yeah! We are going to join your party!", guest_join_path(@guest, :visit => "yes"), class: "col-md-4 col-md-offset-2 btn btn-success btn-lg" %>
    <%= link_to "Sorry, we can't join you.", guest_join_path(@guest, :visit => "no"), class: "col-md-4 col-md-offset-1 btn btn-danger btn-lg" %>
  </div>
</div>
<div class="free-space"></div>

app/views/guests/upset.html.erb
<div class="container">
  <h1>Oh Noooo... (((</h1>
<h2>Ok, at least bring the gifts and get out.</h2>
<%= image_tag('upset2.gif', class:'fireworks img-thumbnail') %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZakharBirthday</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Guests list</h1>

<%= link_to guests_path, "guests" %>